word_dict = {'Fruit': ['apple', 'mango', 'strawberry', 'kiwi', 'papaya', 'pineapple', 'watermelon ', 'muskmelon', 'plum', 'melon', 'lemon', 'orange', 'banana', 'avocado', 'cherry', 'raspberry', 'blueberry', 'custard apple', 'grapes', 'pomegranate', 'apricots', 'blackberry', 'blackcurrant', 'cranberry', 'guava', 'honeydew melon', 'jackfruit', 'lychee', 'mandarin', 'mulberry', 'olive', 'passion fruit', 'peaches', 'pear', 'tamarind', 'tangerine', 'soursop', 'rhubarb', 'quince', 'drangonfruit', 'nectarine', 'lime', 'longan', 'loquat', 'kumquat', 'figs', 'carambola', 'clementine', 'durian', 'mangosteen'],
        'Vegetable': ['eggplant', 'asparagus', 'bean sprouts', 'black beans', 'chickpeas', 'green beans', 'kidney beans', 'lentils', 'peanuts', 'soy beans', 'peas', 'broccoli\xa0', 'brussels sprouts', 'cabbage', 'cauliflower', 'fennel', 'spinach', 'mushrooms', 'onions', 'sweet corn', 'pumpkin\xa0', 'beetroot', 'bottle gourd', 'bitter gourd', 'capsicum', 'coconut', 'corn', 'curry leaves', 'lady finger', 'potato', 'chili', 'arrowroot', 'arugula', 'turnip', 'cucumber', 'rumsticks', 'ginger', 'groundnut', 'gourd', 'olives', 'radish', 'soybean', 'tomato', 'watercress', 'zucchini', 'amaranth', 'cassava', 'earthnut', 'french beans', 'nettles'],
        'Hobby': ['photography', 'cooking', 'sewing', 'writing', 'hiking', 'trekking', 'knitting', 'exercise', 'drawing', 'scrapbooking', 'crochet', 'painting', 'origami', 'bird watching', 'hunting', 'shopping', 'camping', 'calligraphy', 'embroidery', 'pottery', 'baking', 'candle making', 'computer programming', 'candy making', 'karaoke', 'quilting', 'coin collecting', 'quilling', 'singing', 'sketching', 'weaving', 'reading', 'meditation', 'travelling', 'driving', 'canoeing', 'palmistry', 'yoga', 'zumba', 'craft', 'video gaming', 'geocaching', 'homebrewing', 'creative writing', 'beekeeping', 'blogging', 'public speaking', 'carving', 'rock painting'],
        'Language': ['english', 'hindi', 'marathi', 'german', 'spanish', 'mandarin', 'arabic', 'russian', 'portuguese', 'japanese', 'bengali', 'javanese', 'french', 'korean', 'turkish', 'tamil', 'telugu', 'vietnamese', 'urdu', 'bulgarian', 'czech', 'gothic', 'greek', 'hawaiian', 'hungarian', 'icelandic', 'hebrew', 'indonesian', 'irish', 'italian', 'chinese', 'albanian', 'ancient greek', 'balti', 'dakota', 'danish', 'dutch', 'hainanese', 'jarawa', 'jutish', 'kashmiri', 'ladin', 'lakota', 'limbu', 'leonese', 'marwari', 'norwegian', 'persian', 'polish', 'quinqui'],
        'Device': ['computer', 'television', 'laptop', 'tablet', 'mobile phone', 'telephone', 'printer', 'paper shredder', 'camera', 'camcorder', 'dvd player', 'video recorder', 'smartphone', 'calculator', 'joystick', 'projector', 'speaker', 'webcam', 'headphones', 'microphone', 'earphones', 'scanner', 'light pen', 'microprocessor', 'hard disk', 'motherboard', 'compact disk', 'pen drive', 'digital versatile disk', 'floppy disk'],
        'Sport': ['acrobatics', 'bowling', 'archery', 'basketball', 'baseball', 'football', 'handball', 'cricket', 'hockey', 'gymnastics', 'karate', 'table tennis', 'tennis', 'ice skating', 'scuba diving', 'fishing', 'golf', 'skiing', 'polo', 'rafting', 'rowing', 'diving', 'swimming', 'weightlifting', 'boxing', 'gliding', 'skysurfing', 'paragliding', 'badminton', 'softball', 'kickball', 'surfing', 'skating', 'skatboarding', 'snowboarding', 'dodgeball', 'frisbee', 'rock climbing', 'rope climbing', 'pole climbing', 'canyoning', 'artistic cycling', 'underwater cycling', 'unicycling', 'judo', 'wrestling', 'sumo', 'kickboxing', 'pool', 'snooker'],
        'Wild Animal': ['lion', 'tiger', 'cheetah', 'leopard', 'elephant', 'polar bear', 'boar', 'bluebird', 'deer', 'flamingo', 'giraffe', 'gorilla', 'hyena', 'iguana', 'jackal', 'jaguar', 'wolf', 'kangaroo', 'koala', 'monkey', 'mammoth', 'mongoose', 'panda', 'penguin', 'ostrich', 'panther', 'reindeer', 'gemsbok', 'ibex', 'oryx', 'zebra', 'komodo dragon', 'tinamou', 'gibbon', 'chimpanzee', 'hippopotamus', 'siberian husky', 'snake', 'walrus', 'pangolin', 'blackbuck', 'rhinoceros', 'wombats', 'felidae', 'wildcat', 'lynxes', 'wildebeest', 'canidae', 'felis', 'warthog', 'dingo', 'caracal', 'gaur', 'gharial', 'wallaby', 'dhole'],
        'Colour': ['orange', 'yellow', 'green', 'blue', 'indigo', 'violet', 'purple', 'pink', 'magenta', 'grey', 'white ', 'black', 'ivory', 'turquoise', 'brown', 'azure', 'beige', 'burgundy', 'byzantium', 'carmine', 'cerise', 'crimson', 'cerulean', 'cyan', 'harlequin', 'jade', 'lilac', 'maroon', 'mauve', 'periwinkle', 'ochre', 'ruby', 'sangria', 'sapphire', 'scarlet', 'silver', 'vidirian', 'amber', 'amethyst', 'emerald', 'erin', 'slate', 'peach', 'sepla', 'bisque', 'celeste', 'fuchsia'],
        'Domestic Animal': ['horse', 'parrot', 'cow', 'sheep', 'guinea pig', 'chipmunk', 'turtle', 'tortoise', 'goat', 'buffalo', 'bull', 'donkey', 'goose', 'rabbit', 'mouse', 'rat', 'mink', 'hedgehog', 'duck', 'goose', 'leech', 'snail', 'sparrow', 'squirrel', 'hamster', 'mule', 'camel', 'turkey', 'rooster', 'foal'],
        'Tourist Attraction': ['taj mahal', 'eiffel tower', 'great wall of china', 'statue of liberty', 'qutub minar', 'big ben', 'colosseum', 'tokyo tower', 'london eye', 'berlin wall', 'kilimanjaro', 'times square', 'hawa mahal', 'amber palace', 'red fort', 'agra fort', 'city palace', 'anand bhavan', 'charminar', 'elephanta caves', 'ellora caves', 'gateway of india', 'golden temple', 'panch mahal', 'pichola lake', 'pangong lake', 'ruins of hampi', 'jama masjid', 'havelock island', 'borra caves', 'tso moriri lake', 'mysore palace', 'loktak lake', 'kodaikanal lake', 'jaigarh fort', 'pattadakal'],}

# for i in tttt.values():
#     lst=[]
#     for j in i.values():
#         lst.append(j)
#
#     print(lst)
